// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zluyplrkrbenqjncwicl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdXlwbHJrcmJlbnFqbmN3aWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODcwMzMsImV4cCI6MjA2Mzg2MzAzM30.lxUtfy45JT9kRZ_sdPABKKpnAYjihWfokB_hfkGDkLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);